    #this is intentinal duplication for future readability
backendPoint:
    host: cloud-vector.suvidhaportal.com
    service: https-server-service
    namespace: internal-backend
    port: 3005
frontendPoint:
    host: cloud-vector.suvidhaportal.com
    service: frontend-service
    namespace: internal-frontend
    port: 3000
gateway:
  selector: ingressgateway
  namespace: istio-system
ingress:
  enabled: false   #  Disable Kubernetes Ingress 

istio:
  enabled: true    #  Enable Istio integration
  gateway:
    enabled: true  #  Deploy Gateway + VirtualService
    name: shared-gateway
    namespace: istio-system

gatewaysListForCertificate:
  frontendWithBackend:
    host: cloud-vector.suvidhaportal.com
    secret: frontend-backend
    namespace: istio-system
  postgres:
    host: pg-cloud-vector.suvidhaportal.com
    secret: postgres
    namespace: tcp-gateway
  redis:
    host: redis-cloud-vector.suvidhaportal.com
    secret: redis
    namespace: tcp-gateway
  rabbitmq:
    host: rabbitmq-cloud-vector.suvidhaportal.com
    secret: rabbitmq
    namespace: tcp-gateway