rabbitAMQPGateway:
    namespace: tcp-gateway
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-rabbit-amqp-gateway
        tag: c79fd2f8fc5a71d69df93f6293430d4955ecdf50
        pullPolicy: Always
        pullSecret: regcred
    ports:
      - name: amqp
        port: 5671
        containerPort: 5671
      - name: http
        port: 9000
        containerPort: 9000
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80