apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-94"
spec:
  replicas: {{ .Values.httpsServer.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
           cloud.google.com/gke-nodepool: prod-cloud-vector-spot-nodes
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.httpsServer.image.repository }}:{{ .Values.httpsServer.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.httpsServer.image.pullPolicy }}
          imagePullSecrets:
            - name: {{ .Values.httpsServer.image.pullSecret }}
          ports:
            - name: {{ .Values.httpsServer.ports.name }}
              port: {{ .Values.httpsServer.ports.port }} 
              containerPort: {{ .Values.httpsServer.ports.containerPort }}
          resources:
            {{- toYaml .Values.httpsServer.resources | nindent 12 }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          envFrom:
           - secretRef:
               name: common-backend-secret