apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-24"
spec:
  replicas: {{ .Values.infraProvisioner.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
           cloud.google.com/gke-nodepool: prod-cloud-vector-spot-nodes
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.infraProvisioner.image.repository }}:{{ .Values.infraProvisioner.image.tag | default .Chart.AppVersion  }}
          imagePullPolicy: {{ .Values.infraProvisioner.image.pullPolicy }}
          ports:
            - name: {{ .Values.infraProvisioner.ports.name }}
              port: {{ .Values.infraProvisioner.ports.port }}
              containerPort: {{ .Values.infraProvisioner.ports.containerPort }}
          resources:
            {{- toYaml .Values.infraProvisioner.resources | nindent 12 }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: common-backend-secret