rabbitmq:
    name: rabbitmq
    rabbitmq_id: 0
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-rabbitmq
        tag: v1
        pullPolicy: IfNotPresent
        pullSecret: regcred
        
    ports:
        name: amqp
        port: 5672
        containerPort: 5672
    syncWave: "-28"
    storage: "1Gi"
    storageClass: standard-rwo
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
