apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}-ini-configmap"
data:
  pgbouncer.ini: |
    [databases]
    * = host={{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}-service port={{ .Values.postgres.service.port }}

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = trust
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    reserve_pool_size = 5
    log_connections = 1
    log_disconnections = 1
    ignore_startup_parameters = extra_float_digits
  userlist.txt: |
    "myvectoruser" ""
