postgresProtocolGateway:
    namespace: control-plane-tcp-gateway
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-postgres-protocol-gateway
        tag: 0de205bb016dc9a550c513bc55f96bfb90913a70
        pullPolicy: Always
        pullSecret: regcred
    ports:
      - name: postgres-wire-protocol
        port: 5432
        containerPort: 5432
      - name: http
        port: 9000
        containerPort: 9000
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80