postgres:
    db_id: 0
    name: postgres
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-postgres
        tag: v1
        pullPolicy: Always
        pullSecret: regcred
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
    service:
        port: 5432
        targetPort: 5432
        type: ClusterIP
    storage: 2Gi
    storageClass: standard-rwo

    backup:
        enabled: false
        schedule: "0 0 * * *"  
        retention: 7           
    pgbouncer:
       service:
         port: 6432
         targetPort: 6432