redisProtocolGateway:
    namespace: control-plane-tcp-gateway
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-redis-protocol-gateway
        tag: cb1c39afaa9d699c5ce58d4335f10ae5b4d7985e
        pullPolicy: Always
        pullSecret: regcred
    ports:  
      - name: redis-protocol
        port: 6379
        containerPort: 6379
      - name: http
        port: 9000
        containerPort: 9000
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80