backendPoint:
  name: common-backend-secret
  namespace: internal-backend
frontendPoint:
  name: frontend-secret
  namespace: internal-frontend
tcpGatewayPoint:
  name: tcp-gateway-secret
  namespace: tcp-gateway