postgres:
    db_id: 0
    name: postgres
    replicasCount: 1
    image:
        repository: ring0exec/cloud-vector-postgres
        tag: v1
        pullPolicy: IfNotPresent
        pullSecret: regcred
    resources:
        requests:
            cpu: "100m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
    service:
        port: 5432
        targetPort: 5432
        type: ClusterIP
    storage: 5Gi

  
    backup:
        enabled: true
        schedule: "0 0 * * *"  
        retention: 7           


env:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgresMbuguv767ug"
  POSTGRES_DB: "postgres"
    